---
title: "Political Science 312 Homework 7"
date: "`r Sys.Date()`"
output:
  html_document:
    highlight: tango
  pdf_document: default
urlcolor: blue
---

```{r include = FALSE}
knitr::opts_chunk$set(
  echo = FALSE,                 # don't show code
  warning = FALSE,              # don't show warnings
  message = FALSE,              # don't show messages (less serious warnings)
  cache = FALSE,                # set to TRUE to save results from last compilation
  fig.align = "center",         # center figures
  attr.source = '.numberLines'  # add line numbers to code
)

library(tidyverse)       # load libraries you always use here

set.seed(27)             # make random results reproducible
```

# Due Date: May 23, 2025

### More Advanced Designs

How could more advanced research designs be used to address the question you're exploring in your project? Could an experiment, a differences-in-differences, a synthetic controls, or some other research design be used to answer your question? How would this answer compare to the one you get from regression with control variables? Think through the relative strengths and weaknesses of each approach you think makes sense for your project.

### Other Limitations

As you come to the end of the quarter, what are the other limitations you can see in the project as you've carried it out? Are there problems with your data, missing variables you would have liked to use, patterns of missingness in the data that you've discovered, or other problems that have come to your attention over the course of working on the project? (Recall that transparency is a social science virtue; disclosing limitations will never hurt your grade in this class.) 
