---
address: 316 Scott Hall, Department of Political Science, Northwestern
  University
author:
- |
  Jaye Seawright\
  j-seawright@northwestern.edu\
  Office Hours: Mondays, 12-2pm
title: Political Science 312, Spring 2025
---

Email: j-seawright@northwestern.edu

# Basic Course Information

How much political violence is there in the average American community, and why is there more in some places than in others? Why can’t Democrats and Republicans just get along? Does a country’s colonial experience shape its future political and economic possibilities? These questions, and many more, have been addressed by statistical research in political science. This course explores quantitative/statistical research methods in the social sciences, with the goal of determining what makes a good descriptive or causal inference about politics. In this course, we will review the basics of statistical theory and quantitative research design, and then we will proceed to carefully examine in practical terms how to carry out and particularly analyze a quantitative study in political science.

Throughout the quarter, you will work with a team on hands-on projects involving a real-world political-science research question and data set. In the process, you will learn not only how to evaluate other people’s statistical work, but also how to design, execute, and interpret your own statistical models.

By the end of the course, students will:

- be expected to design, implement, execute, and interpret their own research project in statistical social science;
- present results in a clear and interpretable way using graphs and tables, and also interpret and critique the graphs and tables used in other people’s quantitative social science work;
- explain the key assumptions behind common forms of statistical analysis in social science, and be able to perform common tests to check whether those assumptions are plausible in a given application;
- identify the implications of statistical results for social science causal theories; and
- clearly and concisely explain statistical results to an audience.

Grades will be based on seven weekly hands-on group assignments (5% each for a total of 35%), in-class exercises and activities (35%), and a final group presentation (30%).

# Assignments

There are three categories of assignments spread throughout the quarter. First are weekly hands-on assignments (35% of the total grade). These are a set of activities that you will carry out together with a stable research group to gradually develop a project that asks and answers a social-science question using the methods of quantitative research. The assignments are designed to split the process into manageable steps and generate measurable progress across the course of the quarter.

Second are the in-class exercises listed in the syllabus below (35% of the total grade). Some of these tie into the group project, while others are more scripted exercises. Each of them is designed to give you hands-on experience with a particular topic and to help you develop the concrete skills that define expertise in quantitative research methods for the purposes of, but also beyond, the project you are carrying out this quarter.

Third, your final group project will be a presentation of your original quantitative social-science research analyzing a question of your choosing (30% of the total grade). The format will be that of a professional presentation as at a social-science conference. This means you will speak for 12-15 minutes, presenting:

1.  The question and motivation for your project

2.  Existing literature and the reasons why your project has a contribution to offer

3.  Your research design and data

4.  Your results, including evidence in favor of your research design, but also evidence of potential limitations

5.  Conclusions; what we have learned, next steps, and implications for scholars and the general public

Projects will be evaluated based on:

  - Using one of the research designs for causal inference discussed in class
  - Carefully considering and presenting evidence about assumptions
  - Professionalism and clarity of slides and presentation
  - Creativity
  - Use and quality of graphs and tables
  - Handling questions from discussant and Q&A with clarity, precision, and professionalism

For the class sessions that will serve as our mini-conference, students will have the opportunity to volunteer as discussants for other groups. Discussants will receive the other group's slides at least 1 hour before class. They will review them and prepare a 3-4 minute feedback presentation. This presentation will highlight things the group does well, but also areas that could use further development as well as unanswered or incompletely answered questions. Students who volunteer as discussants will receive 1% extra credit for the course, and those who perform the role well will receive an extra 1%.
  
# Northwestern University Syllabus Standards 

This course follows the [Northwestern University Syllabus Standards](https://www.registrar.northwestern.edu/registration-graduation/northwestern-university-syllabus-standards.html). Students are responsible for familiarizing themselves with this information. 

# Course Schedule and Readings

This schedule is subject to changes (minor or major) depending on how
long each topic actually takes us to cover, as well as on the needs of
the class.

The main textbook for this course is The Effect by Nick Huntington-Klein, hosted for free at [https://theeffectbook.net/](https://theeffectbook.net/). The two chapters we use from Quan Li's book, Using R for Data Analysis in Social Sciences : A Research Project-Oriented Approach, are available in .pdf format on the course Canvas site at 

**Thursday, April 2nd: Finding Good Questions in Statistical Social Science**

Before class, read The Effect, Chapters 1-2.

Class activity: We will brainstorm a list of topics that social scientists study, and you will cluster yourselves into groups of 3-5 based on interest in specific topics. Then your job is to find a good quantitative research question connected to that topic. Each student will then send their TA an email describing that question and why they think it will work.

**Tuesday, April 7th: Getting Started with R**

Before class, read: [Li, Chapters 1-2](InClass/LiCh1and2.pdf)

If you are new to R, work through the [online introduction](https://rpubs.com/odenipinedo/introduction-to-R).

It may be helpful to have a video introduction; I recommend [this one](https://www.youtube.com/watch?v=eYv_UjKwQ3I).

Class activity:  Get together with your group from last time. Your task is to recreate one of the graphs [this web tutorial](https://rforpoliticalscience.com/2024/04/04/how-to-download-and-graph-the-of-democracy-v-dem-dataset-in-r/), either following its steps exactly or changing one or more of the variables to ask a question from the V-DEM data that interests your group. (Focus on producing a clear, static graph for this assignment.) Each group member should send the resulting image to their TA along with a brief paragraph describing the most difficult part of producing it.

**Thursday, April 9th: Causation and Causal Inference**

Before class, read The Effect, Chapters 5-7.

For some extra explanation of the idea of multivariate causation and how that relates to graphs, consider watching [this video](https://www.youtube.com/watch?v=3bUZU23gAxw).

For a nice resource on how to build DAGs in R, consider reading through [these slides](https://lfoswald.github.io/2021-spring-stats2/materials/session-3/03-online-tutorial/#directed-acyclic-graphs-dags-1).

Class activity: Construct a directed acyclic graph (DAG) representing your ideas about the causal factors involved in your team's research question. Each group member should send the DAG to their TA together with a paragraph or two explaining what each element of the image means.

**Tuesday, April 14th: Regression**

Before class, read The Effect, Chapters 4 and 13.

For video explanation, consider these discussions of [linear regression](https://www.youtube.com/watch?v=7ArmBVF2dCs), [multiple regression](https://www.youtube.com/watch?v=zITIFTsivN8), and [how to do regression in R](https://www.youtube.com/watch?v=hokALdIst8k).

Class activity: How does electoral support for Donald Trump in 2016 relate to the pattern of domestic terrorism in the US in subsequent years? Is there more terrorism in Trump-supporting areas or in areas that oppose Trump? Alternatively, is terrorism unrelated to voting patterns? Use the available data and your knowledge of regression to provide the best analysis of these questions that you can. Produce one table and one figure to summarize your key findings. Each group member should send these together with a paragraph-length explanation to their TA.

**Thursday, April 16th: Choosing Control Variables**

Before class, watch [this video about back-door paths and controls](https://www.youtube.com/watch?v=IajzIKW518M).

Class activity: Elaborate the group's DAG to include appropriate control variables. Show at least three variables that make sense as confounders. Each student should send the DAG to their TA. Include as well an explanation for why one of the variables meets the definition of a confounder; also explain why one variable the group chose not to include does not meet that definition.

**Tuesday, April 21st: More Advanced Social-Science Designs**

Before class, read The Effect, Chapters 18-21

Here is [a quick video explanation of the idea of natural experiments in political science](https://www.youtube.com/watch?v=1nt8ATK3s-k). Here is a helpful and short, if a bit older, [video introduction to regression-discontinuity designs](https://www.youtube.com/watch?v=gLAlb78p0Fk), [instrumental variables](https://www.youtube.com/watch?v=J2BMFBMO14o), and [difference-in-differences](https://www.youtube.com/watch?v=XFqFH97bDy4).

Class activity: For your group's research question, choose one of the designs we read about/discussed and figure out a way you can use it to answer your question! Each student should write a paragraph to their TA explaining the design they have chosen and why they think it can work.

**Thursday, April 23rd: Difference-in-Differences**

Before class, read
<https://mixtape.scunning.com/09-difference_in_differences>

I also recommend video explanations of [basic difference-in-differences](https://www.youtube.com/watch?v=95HxUdn-BJg), [parallel trends](https://www.youtube.com/watch?v=ihIWuC6ULjo), and [difference-in-differences with staggered treatments](https://www.youtube.com/watch?v=hu2nDbnpALA).

Class activity: Does transitioning to democracy increase the chance of
military conflict? We can study this with a difference-in-differences
design using historical data on countries' regimes and conflicts, and
you get to do just that. Test as many of your assumptions as you can,
and explain what you learn!

**Tuesday, April 28th: Synthetic Control**

Before class, read <https://mixtape.scunning.com/10-synthetic_controls>

Here is [a helpful and thorough video introduction to synthetic controls](https://www.youtube.com/watch?v=vmx3R8emVjQ).

Class activity: Did Brexit in 2016 set the UK on a path of democratic
backsliding? We can study this with a synthetic control design using
historical data on countries' regimes, and you get to do just that.
Present graphs and other results to explain your analysis, showing the
quality of the control before the treatment as well as the size of any
effect afterwards.

**Thursday, April 30th: Regression-Discontinuity Designs**

Before class, read
<https://mixtape.scunning.com/06-regression_discontinuity>

For video discussion, watch this [introductory video on regression-discontinuity designs](https://www.youtube.com/watch?v=5FM4-xbaS58), this one on [estimating RDD effects](https://www.youtube.com/watch?v=FPBQL0OKmI0), this one on [adjustments to RDD](https://www.youtube.com/watch?v=3HazJ8Tv6d0), and this one on [checking RDD assumptions](https://www.youtube.com/watch?v=WJ7j08xVegY).

Class activity: Is ideological polarization in the US happening equally on both sides of the party system, or do the parties behave differently in terms of their distance from the ideological middle? Let's try to get an answer to this that cleans up some of the background noise by using a regression-discontinuity design. We'll compare close elections that Republicans just barely win to close elections that Democrats just barely win and look at the absolute value of the resulting ideological distance from the middle of the elected representatives. Working with your group, find numerical estimates of the effect of switching party within this design, significance tests, and a plot that visualizes the results, the underlying data, and the design. Send these, together with a brief description of your conclusions, to your TA.

**Tuesday, May 5th: Instrumental Variables Designs**

Before class, read
<https://mixtape.scunning.com/07-instrumental_variables>

I also recommend watching this [helpful video explanation of instrumental variables](https://www.youtube.com/watch?v=eoJUPd6104Q).

Class activity: Does higher turnout help Democrats, Republicans, both, or neither? Let's try to find out by using bad weather as an instrumental variable to predict turnout. Run a standard regression predicting Republican vote share based on turnout, and also an instrumental-variables analysis adding rain- and snow-fall as instruments. Are there differences between the two? Are there signs of trouble for the instruments, or do they seem reasonable? Examine Google Scholar to see how popular instruments like these are in the social sciences. What, if anything, can we conclude about the validity of these as instruments from the applications you have seen? Each student should write a brief description of the findings and an evaluation of the credibility of the analysis and send the results to their TA.

**Thursday, May 7th: Social Science Transparency Practices**

Before class, read Christensen, Garret, Zenan Wang, Elizabeth Levy
Paluck, Nicholas Swanson, David Birke, Edward Miguel, and Rebecca
Littman."Open science practices are on the rise: The state of social
science (3S) survey." (2020).
<https://escholarship.org/uc/item/0hx0207r>

It may also be productive to watch this [reasonably long but very informative talk on open social science](https://www.youtube.com/watch?v=CJ0kPic7fjA).

Class activity: for a research question randomly provided for your
group, find at least five published quantitative articles and evaluate
the transparency practices of those articles. Was there preregistration,
are data and code available for replication, etc.? Search for at least
one preregistration form related to the research question to see the
format of such documents.

**Tuesday, May 12th: Missing Data**

Before class, read [this overview of the problem of missing data.](https://www.publichealth.columbia.edu/research/population-health-methods/missing-data-and-multiple-imputation)

You may also get value out of [this video explanation of categories of missingness](https://www.youtube.com/watch?v=UzsWr9X98J8), as well as [this introduction to multiple imputation](https://www.youtube.com/watch?v=f6YLnK27LyE).

Class activity: Let's look at whether missing data are a problem in the study of democracy and economic development. With your group, access the Quality of Governance (QoG) dataset, and assemble a regression model predicting countries' level of democracy based on per capita GDP and any control variables you see as relevant. Are there missing data? What are some possible solutions? Show how implementing a good solution would modify the results (if at all). Each student should send a table showing the original regression results and the results correcting for missing data to their TA, along with a paragraph discussing the extent to which missing data made a difference in the results.

**Thursday, May 14th: Common Pitfalls**

Before class, read [this inventory of common mistakes in quantitative research.](https://pmc.ncbi.nlm.nih.gov/articles/PMC9477699/)

You may also find [this related and partially overlapping video about statistical fallacies](https://www.youtube.com/watch?v=zzJgn12le4Q) useful.

Class activity: What would it look like for your group project this quarter to make each of the mistakes we've highlighted this week? Describe the worst-case scenario where you would fall into each pitfall, and discuss how you can avoid that. As a group, create a table with three columns: the name of the pitfall, a sketch of the scenario where your project would really be subject to that criticism, and a set of precautions you can take to avoid that. Send this table to each TA together with the names of the group members.

**Tuesday, May 19th: Writing Quantitative Social Science**

Before class, read BOTH [Daniel M Butler, Elin Naurin, and Patrik
Öhberg, "Constituents Ask Female Legislators to do More." *The Journal
of Politics*. Forthcoming.
https://doi.org/10.1086/719631](https://doi.org/10.1086/719631)

AND

[Noam Lupu and Leonid Peisakhin, 2017, "The Legacy of Political Violence
across Generations." *American Journal of Political Science* 61 (Oct.):
836-51.](https://doi.org/10.1111/ajps.12327)

It will also be exceptionally helpful if you take the seven minutes to watch this careful video on [how to structure social-science papers](https://www.youtube.com/watch?v=6xVNhIRPTt8).

We will discuss together the features of well-written quantitative
social science, and how to structure a successful paper/article in this
genre.

**Thursday, May 21st: In-Class Presentations Day 1**

If your group did not present on this day, please send your TA a summary of your participation. This may take three forms. First, if you were a discussant for one of the presentations, you can mention that. Second, if you participated in one or more Q&A sessions, describe your participation. Third, because there may not always be time for everyone to actively speak in every session, you can write a couple of paragraphs discussing what you saw as the strengths and weaknesses of today's presentations.

**Tuesday, May 26th: In-Class Presentations Day 2**

If your group did not present on this day, please send your TA a summary of your participation. This may take three forms. First, if you were a discussant for one of the presentations, you can mention that. Second, if you participated in one or more Q&A sessions, describe your participation. Third, because there may not always be time for everyone to actively speak in every session, you can write a couple of paragraphs discussing what you saw as the strengths and weaknesses of today's presentations.

**Thursday, May 28th: In-Class Presentations Day 3**

If your group did not present on this day, please send your TA a summary of your participation. This may take three forms. First, if you were a discussant for one of the presentations, you can mention that. Second, if you participated in one or more Q&A sessions, describe your participation. Third, because there may not always be time for everyone to actively speak in every session, you can write a couple of paragraphs discussing what you saw as the strengths and weaknesses of today's presentations.

**Tuesday, June 2nd: In-Class Presentations Day 4**

If your group did not present on this day, please send your TA a summary of your participation. This may take three forms. First, if you were a discussant for one of the presentations, you can mention that. Second, if you participated in one or more Q&A sessions, describe your participation. Third, because there may not always be time for everyone to actively speak in every session, you can write a couple of paragraphs discussing what you saw as the strengths and weaknesses of today's presentations.
