---
title: "Political Science 312 Homework 1"
date: "`r Sys.Date()`"
output:
  html_document:
    highlight: tango
  pdf_document: default
urlcolor: blue
---

```{r include = FALSE}
knitr::opts_chunk$set(
  echo = FALSE,                 # don't show code
  warning = FALSE,              # don't show warnings
  message = FALSE,              # don't show messages (less serious warnings)
  cache = FALSE,                # set to TRUE to save results from last compilation
  fig.align = "center",         # center figures
  attr.source = '.numberLines'  # add line numbers to code
)

library(tidyverse)       # load libraries you always use here

set.seed(27)             # make random results reproducible
```

# Due Date: April 17, 2026

Working together as a group, please answer the following questions. Each group member should submit a copy, but it is okay for the writing to be the same across group members.

# Problem 1: Choosing a Causal Question

Within the research topic that brings your group together, it is essential that you focus in on a causal question to motivate your research. Explain your causal question, describing the independent and dependent variables and why you as a group think this will be a worthwhile question to pursue.

# Problem 2: Existing Literature

On Google Scholar or some related resource, I'd like you to search for existing quantitative social science studies on your question or related topics. What have people already learned, and what is not yet clear? It's okay if there is already some work on your question; this just means other people find it interesting! There will still be room for you to make a contribution.

