---
title: "Political Science 312 Homework 7"
date: "`r Sys.Date()`"
output:
  html_document:
    highlight: tango
  pdf_document: default
urlcolor: blue
---

```{r include = FALSE}
knitr::opts_chunk$set(
  echo = FALSE,                 # don't show code
  warning = FALSE,              # don't show warnings
  message = FALSE,              # don't show messages (less serious warnings)
  cache = FALSE,                # set to TRUE to save results from last compilation
  fig.align = "center",         # center figures
  attr.source = '.numberLines'  # add line numbers to code
)

library(tidyverse)       # load libraries you always use here

set.seed(27)             # make random results reproducible
```

# Due Date: May 29, 2026

[Submit your lab here.](https://canvas.northwestern.edu/courses/251652/assignments/1730884)

### Next Steps

What are the next steps you would like to see taken to further your research agenda and solidify our knowledge given your contribution? Identify at least three directions scholars could productively go in order to build on your work or address the limitations of your project. What would you do differently if you started the project over? What are the biggest strengths and weaknesses of your research design, as it turns out?

Part of professional communication is developing a section in your conclusion that spells out the limitations of your work, good ways to resolve those limitations, and the opportunities your work provides for future learning. Draft two to three paragraphs that provide such a conclusion.
